### ISSUE TITLE
Getting a lot of errors in the syslog due to untrusted user accessing nix-daemon

### ISSUE THREAD

**Issue by oddlama** [symphorien/nixseparatedebuginfod#11]
I'm getting a huge amount of errors in my syslog when installing [nixseparatedebuginfod](https://github.com/symphorien/nixseparatedebuginfod). Did I miss something essential?

If I read this right, `DynamicUser = true` is set unconditionally on the service (which is good), but which also would explain why it throws all these errors.

```
Sep 20 23:26:05 kroma nixseparatedebuginfod[3206]: 2023-09-20T21:26:05.185552Z  WARN indexing{storepath=/nix/store/54166khdzm8sp6bc4791vpxgqms3s2sn-gjs-1.76.2-debug}: nixseparatedebuginfod::store: no deriver for /nix/store/54166khdzm8sp6bc>
Sep 20 23:26:05 kroma nix-daemon[3200]: error: error processing connection: user 'nixseparatedebuginfod' is not allowed to connect to the Nix daemon
Sep 20 23:26:05 kroma nixseparatedebuginfod[3206]: 2023-09-20T21:26:05.188582Z  WARN indexing{storepath=/nix/store/4lnal7glzzbbasm4msg9lzf3ywim07lz-gjs-1.76.2-installedTests}: nixseparatedebuginfod::store: no deriver for /nix/store/4lnal7g>
Sep 20 23:26:05 kroma nix-daemon[3200]: error: error processing connection: user 'nixseparatedebuginfod' is not allowed to connect to the Nix daemon
Sep 20 23:26:05 kroma nixseparatedebuginfod[3206]: 2023-09-20T21:26:05.408136Z  WARN indexing{storepath=/nix/store/qy0sqz0dq9z5rwiw46na5l3k3rjgpym7-mutter-44.3-debug}: nixseparatedebuginfod::store: no deriver for /nix/store/qy0sqz0dq9z5rwi>
Sep 20 23:26:05 kroma nix-daemon[3200]: error: error processing connection: user 'nixseparatedebuginfod' is not allowed to connect to the Nix daemon
Sep 20 23:26:05 kroma nixseparatedebuginfod[3206]: 2023-09-20T21:26:05.415322Z  WARN indexing{storepath=/nix/store/dn5h8mpfk0ldbxabc3dagxmgb8rk8y0l-mutter-44.3}: nixseparatedebuginfod::store: no deriver for /nix/store/dn5h8mpfk0ldbxabc3dag>
Sep 20 23:26:06 kroma nix-daemon[3200]: error: error processing connection: user 'nixseparatedebuginfod' is not allowed to connect to the Nix daemon
Sep 20 23:26:06 kroma nixseparatedebuginfod[3206]: 2023-09-20T21:26:06.246816Z  WARN indexing{storepath=/nix/store/s5zwxh7kzby6rghl6df6li4gfwwjl85i-source}: nixseparatedebuginfod::store: no deriver for /nix/store/s5zwxh7kzby6rghl6df6li4gfw>
Sep 20 23:26:06 kroma nix-daemon[3200]: error: error processing connection: user 'nixseparatedebuginfod' is not allowed to connect to the Nix daemon 
[...]
```

**Comment by symphorien** [comment]
Can you check that `nix show-config` mentions `allowed-users = *` ?

**Comment by oddlama** [comment]
Ah I only have `allowed-users = @wheel` in my config, that should explain it. Do you think that should be configured by the module automatically or should I just add it manually?

**Comment by symphorien** [comment]
Unfortunately if I add `    nix.settings.allowed-users = [ "nixseparatedebuginfod" ];` to the module then this overwrites the default `*` which results in only nixseparatedebuginfod being allowed.

**Comment by oddlama** [comment]
I see. Could you add a short notice to the readme that this needs to be set in case the user set's `allowed-users`?

**Comment by symphorien** [comment]
done

**Comment by oddlama** [comment]
FYI: Just tested this, this also requires using a distinct system-level user instead of `DynamicUser=true`, otherwise adding to allowed-users doesn't work.

Allocated an issue in nix for it: https://github.com/NixOS/nix/issues/9071

**Comment by symphorien** [comment]
I modified the module to handle this situation. To avoid the circular dependency, I use an assertion. Can you try 466110a37e11a33a3551b44d9da5e323a8924cfa ?

**Comment by oddlama** [comment]
Thanks, can confirm that it works nicely. This is pretty much doing exactly what I've been doing manually before :).
