### ISSUE TITLE
Tries to allocate 5.6EB of memory when parsing `yara.src`

### ISSUE THREAD

**Issue by K900** [symphorien/nixseparatedebuginfod#13]
Haven't really investigated yet, but it crashes on startup with 

```
Feb 05 12:09:17 sayaka-wsl nixseparatedebuginfod[2802696]: 2024-02-05T09:09:17.343017Z  INFO nixseparatedebuginfod::store: detected nix >= 2.18
Feb 05 12:09:17 sayaka-wsl nixseparatedebuginfod[2802696]: 2024-02-05T09:09:17.346927Z  INFO nixseparatedebuginfod::index: Starting indexation of new store paths
Feb 05 12:09:17 sayaka-wsl nixseparatedebuginfod[2802696]: memory allocation of 5644418395173552131 bytes failed
```

**Comment by K900** [comment]
Tracked it down to `yara.src`, or `/nix/store/8gq59vnkg6xv2d1hp62m3k3n7rdip2qx-source`, which contains some [interesting stuff](https://github.com/VirusTotal/yara/tree/master/tests/oss-fuzz/elf_fuzzer_corpus)

**Comment by symphorien** [comment]
thank you, the issue is in the object crate https://github.com/gimli-rs/object/issues/204
I can fix it for this instance at least, https://github.com/gimli-rs/object/pull/630
