### ISSUE TITLE
Interface with dwarffs-style queries

### ISSUE THREAD

**Issue by Luabee** [symphorien/nixseparatedebuginfod#3]
Hello! Right now the README.md claims that .drv files will be substituted if they don't exist on the local system. ~This isn't actually true. Passing a .drv path to `nix-store --realize` will attempt to substitute the default output, rather than the .drv file itself. Therefore, if .drv files aren't installed on the same system as the daemon, nothing will work as intended.~

~At my organization we copy system closures to our assets and then install, rather than using `nixos-rebuild`. This means the .drv files are not present.~

Would it be possible to extend nixseparatedebuginfod to query the [/debuginfo url](https://cache.nixos.org/debuginfo/bde350fa1f1bbde3649bfce3ae143b87683d8bf9) of a binary cache just like how dwarffs does? Then you wouldn't need to access the .drv file to map between the debug-id and the debug-output nix store path.

**Comment by symphorien** [comment]
It seems to me that nix-store --realize does copy the .drv file:
I instantiated grub1, copied the drv file to /tmp/cache, and then removed the drv file from my store. Then `nix-store --realize` does work: 
```
$  sudo nix-store -r --extra-substituters file:///tmp/cache /nix/store/ak1m76c0llw7szwf12k59aaz4n578igw-grub-0.97-73.drv
don't know how to build these paths:
  /nix/store/ak1m76c0llw7szwf12k59aaz4n578igw-grub-0.97-73.drv
copying path '/nix/store/ak1m76c0llw7szwf12k59aaz4n578igw-grub-0.97-73.drv' from 'file:///tmp/cache'...
copying path '/nix/store/maijcnjjbwppp4vapn9pn9gzwrqa878i-grub-0.97-73' from 'https://cache.nixos.org'...
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/maijcnjjbwppp4vapn9pn9gzwrqa878i-grub-0.97-73
                                                                                                                                                                                             
~/src/nixpkgs nixos-unstable* ▼ 8s 
$  ls /nix/store/ak1m76c0llw7szwf12k59aaz4n578igw-grub-0.97-73.drv
/nix/store/ak1m76c0llw7szwf12k59aaz4n578igw-grub-0.97-73.drv
```
Can you double check what happens in your setup?

Also the fact that it also downloads the default output might be a bit wasteful, I'll have to think about it. Do you know of an alternative? (if possible not using the unstable nix command)

~~~~

About hitting the same endpoints as dwarffs, it's probably a good idea. My original goal was to have something that works for the local store, and not only with hydra, but that does not preclude taking advantage of hydra indeed.

**Comment by symphorien** [comment]
Apparently I can use a terrible trick to only download the drv file without the output: request a non existing output
```
~/src/nixpkgs nixos-unstable* ▼ 6s 
$  ls /nix/store/ak1m76c0llw7szwf12k59aaz4n578igw-grub-0.97-73.drv
ls: impossible d'accéder à '/nix/store/ak1m76c0llw7szwf12k59aaz4n578igw-grub-0.97-73.drv': No such file or directory
                                                                                                                                                                                             
~/src/nixpkgs nixos-unstable* ▼ 
$  sudo nix-store -r --extra-substituters file:///tmp/cache '/nix/store/ak1m76c0llw7szwf12k59aaz4n578igw-grub-0.97-73.drv!doesnotexist'    
don't know how to build these paths:
  /nix/store/ak1m76c0llw7szwf12k59aaz4n578igw-grub-0.97-73.drv
copying path '/nix/store/ak1m76c0llw7szwf12k59aaz4n578igw-grub-0.97-73.drv' from 'file:///tmp/cache'...
error: derivation '/nix/store/ak1m76c0llw7szwf12k59aaz4n578igw-grub-0.97-73.drv' does not have wanted outputs 'doesnotexist'
                                                                                                                                                                                             
~/src/nixpkgs nixos-unstable* ▼ 
$  ls /nix/store/ak1m76c0llw7szwf12k59aaz4n578igw-grub-0.97-73.drv                                                                         
/nix/store/ak1m76c0llw7szwf12k59aaz4n578igw-grub-0.97-73.drv
```
nix can only know whether the output exists by downloading the drv file...

**Comment by Luabee** [comment]
> It seems to me that nix-store --realize does copy the .drv file: I instantiated grub1, copied the drv file to /tmp/cache, and then removed the drv file from my store. Then `nix-store --realize` does work:
> ...
> Can you double check what happens in your setup?

Ah, I was too focused on the fact that the default output was being realized that I didn't notice the .drv file came with it.


> Apparently I can use a terrible trick to only download the drv file without the output: request a non existing output
> 
> nix can only know whether the output exists by downloading the drv file...

Oh that is nasty. I love it.

**Comment by symphorien** [comment]
Leaving the feature request "hit the same API as dwarffs" aside, can you investigate deeper what does not work in your setup?
what nixseparatedebuginfod does is more or less:
- for each store path that has an elf file, run nix-store --query --deriver to obtain the .drv file
- download it if necessary
- register if it has a debug output

Even though the current way to download the .drv is clumsy, it works as far as I can tell so I would really like to know what does not work.

**Comment by Luabee** [comment]
Hey, yeah I looked closer and I was mistaken about my problem. I wasn't set up to realize .drv files because they didn't exist on the caches I was hitting

So basically this just becomes "hit the same API as dwarffs" :sweat_smile:

**Comment by symphorien** [comment]
So you were right about substituting .drv files, it got lost in a refactoring before I released the initial version I think, and it was not implemented. I implemented it. I'll have a look at the hydra API next month probably.

**Comment by symphorien** [comment]
I implemented the same API as dwarffs on current master. Feel free to reopen if it does not work for you :)
