### ISSUE TITLE
README appears out of date

### ISSUE THREAD

**Issue by kjeremy** [symphorien/nixseparatedebuginfod#4]
I had to explicitly enable the service in my `flake.nix`:

```nix
nixseparatedebuginfod.nixosModules.default { services.nixseparatedebuginfod.enable = true; }
```

Contrary to the current documentation it also looks like a modified `gdb` is installed in `systemPackages`.

**Comment by symphorien** [comment]
I forgot to document the option, which defaults to false ;)
Can you tell me if https://github.com/symphorien/nixseparatedebuginfod/pull/5 seems better?
